Repository adobe/S3Mock, pull requests merged in 2022-09, with the labels that each got.

#787 Correctly detect and use existing root folder
  CHANGELOG.md
  server/src/main/java/com/adobe/testing/s3mock/store/StoreConfiguration.java
Labels: bug

#788 Remove Spring Component Indexes
  CHANGELOG.md
  server/pom.xml
Labels: bug

#791 Allow customers to create ContextConfigurations.
  CHANGELOG.md
  server/src/main/java/com/adobe/testing/s3mock/S3MockConfiguration.java
  server/src/main/java/com/adobe/testing/s3mock/S3MockProperties.java
  server/src/main/java/com/adobe/testing/s3mock/store/StoreConfiguration.java
  server/src/main/java/com/adobe/testing/s3mock/store/StoreProperties.java
Labels: feature

#797 Add support for Retention APIs
  CHANGELOG.md
  README.md
  build-config/pom.xml
  docker/pom.xml
  integration-tests/pom.xml
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/LegalHoldV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PlainHttpIT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/RetentionV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
  pom.xml
  server/pom.xml
  server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
  server/src/main/java/com/adobe/testing/s3mock/S3Exception.java
  server/src/main/java/com/adobe/testing/s3mock/dto/CopySource.java
  server/src/main/java/com/adobe/testing/s3mock/dto/InstantDeserializer.java
  server/src/main/java/com/adobe/testing/s3mock/dto/InstantSerializer.java
  server/src/main/java/com/adobe/testing/s3mock/dto/Retention.java
  server/src/main/java/com/adobe/testing/s3mock/service/BucketService.java
  server/src/main/java/com/adobe/testing/s3mock/service/ObjectService.java
  server/src/main/java/com/adobe/testing/s3mock/store/ObjectStore.java
  server/src/main/java/com/adobe/testing/s3mock/store/S3ObjectMetadata.java
  server/src/main/java/com/adobe/testing/s3mock/util/AwsHttpParameters.java
  server/src/main/java/com/adobe/testing/s3mock/util/StringEncoding.java
  server/src/test/java/com/adobe/testing/s3mock/dto/DtoTestUtil.java
  server/src/test/java/com/adobe/testing/s3mock/dto/RetentionTest.java
  server/src/test/java/com/adobe/testing/s3mock/service/BucketServiceTest.java
  server/src/test/java/com/adobe/testing/s3mock/store/ObjectStoreTest.java
  server/src/test/java/com/adobe/testing/s3mock/util/StringEncodingTest.java
  server/src/test/resources/com/adobe/testing/s3mock/dto/RetentionTest_testDeserialization.xml
  server/src/test/resources/com/adobe/testing/s3mock/dto/RetentionTest_testSerialization.xml
  testsupport/common/pom.xml
  testsupport/junit4/pom.xml
  testsupport/junit5/pom.xml
  testsupport/pom.xml
  testsupport/testcontainers/pom.xml
  testsupport/testng/pom.xml
Labels: feature

#802 ETags in requests and responses must comply to RFC-2616
  server/src/main/java/com/adobe/testing/s3mock/dto/CompleteMultipartUploadResult.java
  server/src/main/java/com/adobe/testing/s3mock/dto/CopyObjectResult.java
  server/src/main/java/com/adobe/testing/s3mock/dto/CopyPartResult.java
  server/src/main/java/com/adobe/testing/s3mock/dto/S3Object.java
  server/src/test/resources/com/adobe/testing/s3mock/dto/ListBucketResultTest_testSerialization.xml
  server/src/test/resources/com/adobe/testing/s3mock/dto/ListBucketResultV2Test_testSerialization.xml
Labels: bug

#820 Various IntegrationTest refactorings
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AmazonClientUploadV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketTestsV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketTestsV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ConcurrencyIT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ErrorResponsesV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ErrorResponsesV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/LegalHoldV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1MaxKeysIT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1PaginationIT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ObjectTaggingV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ObjectTaggingV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PlainHttpIT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/RetentionV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
Labels: housekeeping

#827 LastModified must be updated when copying an object onto itself.
  CHANGELOG.md
  integration-tests/pom.xml
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
  server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
  server/src/main/java/com/adobe/testing/s3mock/store/ObjectStore.java
Labels: bug

#828 Handle all incoming and outgoing ETags according to RFC2616 / RFC7232
  CHANGELOG.md
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketTestsV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketTestsV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/CopyObjectV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ErrorResponsesV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ErrorResponsesV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/GetPutDeleteObjectV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/LegalHoldV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1MaxKeysIT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ListObjectV1PaginationIT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/MultiPartUploadV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ObjectTaggingV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/ObjectTaggingV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/PlainHttpIT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/RetentionV2IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/S3TestBase.kt
  server/src/main/java/com/adobe/testing/s3mock/MultipartController.java
  server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
  server/src/main/java/com/adobe/testing/s3mock/S3Exception.java
  server/src/main/java/com/adobe/testing/s3mock/dto/CompleteMultipartUploadResult.java
  server/src/main/java/com/adobe/testing/s3mock/dto/CompletedPart.java
  server/src/main/java/com/adobe/testing/s3mock/dto/CopyObjectResult.java
  server/src/main/java/com/adobe/testing/s3mock/dto/CopyPartResult.java
  server/src/main/java/com/adobe/testing/s3mock/dto/EtagDeserializer.java
  server/src/main/java/com/adobe/testing/s3mock/dto/EtagSerializer.java
  server/src/main/java/com/adobe/testing/s3mock/dto/ListBucketResult.java
  server/src/main/java/com/adobe/testing/s3mock/dto/ListBucketResultV2.java
  server/src/main/java/com/adobe/testing/s3mock/dto/Part.java
  server/src/main/java/com/adobe/testing/s3mock/dto/S3Object.java
  server/src/main/java/com/adobe/testing/s3mock/service/MultipartService.java
  server/src/main/java/com/adobe/testing/s3mock/service/ObjectService.java
  server/src/main/java/com/adobe/testing/s3mock/store/BucketMetadata.java
  server/src/main/java/com/adobe/testing/s3mock/store/MultipartStore.java
  server/src/main/java/com/adobe/testing/s3mock/store/S3ObjectMetadata.java
  server/src/main/java/com/adobe/testing/s3mock/util/AwsHttpHeaders.java
  server/src/test/java/com/adobe/testing/s3mock/MultipartControllerTest.java
  server/src/test/java/com/adobe/testing/s3mock/ObjectControllerTest.java
  server/src/test/java/com/adobe/testing/s3mock/dto/CompleteMultipartUploadTest.java
  server/src/test/java/com/adobe/testing/s3mock/dto/EtagSerializerTest.java
  server/src/test/java/com/adobe/testing/s3mock/dto/ListBucketResultTest.java
  server/src/test/java/com/adobe/testing/s3mock/dto/ListBucketResultV2Test.java
  server/src/test/java/com/adobe/testing/s3mock/dto/ListPartsResultTest.java
  server/src/test/java/com/adobe/testing/s3mock/service/BucketServiceTest.java
  server/src/test/java/com/adobe/testing/s3mock/service/MultipartServiceTest.java
  server/src/test/java/com/adobe/testing/s3mock/service/ObjectServiceTest.java
  server/src/test/java/com/adobe/testing/s3mock/service/ServiceTestBase.java
  server/src/test/java/com/adobe/testing/s3mock/store/MultipartStoreTest.java
  server/src/test/java/com/adobe/testing/s3mock/store/ObjectStoreTest.java
Labels: bug

#819 Add Get- / Put- ObjectAcl
  CHANGELOG.md
  README.md
  build-config/pom.xml
  docker/pom.xml
  integration-tests/pom.xml
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/AclIT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketTestsV1IT.kt
  pom.xml
  server/pom.xml
  server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
  server/src/main/java/com/adobe/testing/s3mock/dto/AccessControlPolicy.java
  server/src/main/java/com/adobe/testing/s3mock/dto/Grant.java
  server/src/main/java/com/adobe/testing/s3mock/dto/Grantee.java
  server/src/main/java/com/adobe/testing/s3mock/dto/Owner.java
  server/src/main/java/com/adobe/testing/s3mock/dto/Retention.java
  server/src/main/java/com/adobe/testing/s3mock/dto/package-info.java
  server/src/main/java/com/adobe/testing/s3mock/service/ObjectService.java
  server/src/main/java/com/adobe/testing/s3mock/store/MultipartStore.java
  server/src/main/java/com/adobe/testing/s3mock/store/ObjectStore.java
  server/src/main/java/com/adobe/testing/s3mock/store/S3ObjectMetadata.java
  server/src/main/java/com/adobe/testing/s3mock/util/AwsHttpParameters.java
  server/src/main/java/com/adobe/testing/s3mock/util/XmlUtil.java
  server/src/test/java/com/adobe/testing/s3mock/BucketControllerTest.java
  server/src/test/java/com/adobe/testing/s3mock/ContextPathObjectStoreControllerTest.java
  server/src/test/java/com/adobe/testing/s3mock/ObjectControllerTest.java
  server/src/test/java/com/adobe/testing/s3mock/dto/AccessControlPolicyTest.java
  server/src/test/java/com/adobe/testing/s3mock/dto/DtoTestUtil.java
  server/src/test/java/com/adobe/testing/s3mock/dto/ListAllMyBucketsResultTest.java
  server/src/test/java/com/adobe/testing/s3mock/dto/ListBucketResultTest.java
  server/src/test/java/com/adobe/testing/s3mock/dto/ListBucketResultV2Test.java
  server/src/test/java/com/adobe/testing/s3mock/dto/ListMultipartUploadsResultTest.java
  server/src/test/java/com/adobe/testing/s3mock/service/ServiceTestBase.java
  server/src/test/java/com/adobe/testing/s3mock/store/MultipartStoreTest.java
  server/src/test/java/com/adobe/testing/s3mock/store/ObjectStoreTest.java
  server/src/test/resources/com/adobe/testing/s3mock/dto/AccessControlPolicyTest_testDeserialization.xml
  server/src/test/resources/com/adobe/testing/s3mock/dto/AccessControlPolicyTest_testSerialization.xml
  testsupport/common/pom.xml
  testsupport/junit4/pom.xml
  testsupport/junit5/pom.xml
  testsupport/pom.xml
  testsupport/testcontainers/pom.xml
  testsupport/testng/pom.xml
Labels: bug, feature

#838 Avoid root folder temporary directory race condition (closes #837)
  server/src/main/java/com/adobe/testing/s3mock/store/StoreConfiguration.java
Labels: bug

#806 Add Get- / Put- / Delete- BucketLifecycleConfiguration
  CHANGELOG.md
  README.md
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketV1IT.kt
  integration-tests/src/test/kotlin/com/adobe/testing/s3mock/its/BucketV2IT.kt
  server/src/main/java/com/adobe/testing/s3mock/BucketController.java
  server/src/main/java/com/adobe/testing/s3mock/MultipartController.java
  server/src/main/java/com/adobe/testing/s3mock/ObjectController.java
  server/src/main/java/com/adobe/testing/s3mock/S3Exception.java
  server/src/main/java/com/adobe/testing/s3mock/dto/AbortIncompleteMultipartUpload.java
  server/src/main/java/com/adobe/testing/s3mock/dto/BucketLifecycleConfiguration.java
  server/src/main/java/com/adobe/testing/s3mock/dto/LegalHold.java
  server/src/main/java/com/adobe/testing/s3mock/dto/LifecycleExpiration.java
  server/src/main/java/com/adobe/testing/s3mock/dto/LifecycleRule.java
  server/src/main/java/com/adobe/testing/s3mock/dto/LifecycleRuleAndOperator.java
  server/src/main/java/com/adobe/testing/s3mock/dto/LifecycleRuleFilter.java
  server/src/main/java/com/adobe/testing/s3mock/dto/NoncurrentVersionExpiration.java
  server/src/main/java/com/adobe/testing/s3mock/dto/NoncurrentVersionTransition.java
  server/src/main/java/com/adobe/testing/s3mock/dto/Status.java
  server/src/main/java/com/adobe/testing/s3mock/dto/Transition.java
  server/src/main/java/com/adobe/testing/s3mock/service/BucketService.java
  server/src/main/java/com/adobe/testing/s3mock/store/BucketMetadata.java
  server/src/main/java/com/adobe/testing/s3mock/store/BucketStore.java
  server/src/main/java/com/adobe/testing/s3mock/util/AwsHttpParameters.java
  server/src/test/java/com/adobe/testing/s3mock/BucketControllerTest.java
  server/src/test/java/com/adobe/testing/s3mock/dto/BucketLifecycleConfigurationTest.java
  server/src/test/java/com/adobe/testing/s3mock/dto/LegalHoldTest.java
  server/src/test/java/com/adobe/testing/s3mock/store/BucketStoreTest.java
  server/src/test/java/com/adobe/testing/s3mock/store/ObjectStoreTest.java
  server/src/test/resources/com/adobe/testing/s3mock/dto/BucketLifecycleConfigurationTest_testDeserialization.xml
  server/src/test/resources/com/adobe/testing/s3mock/dto/BucketLifecycleConfigurationTest_testSerialization.xml
Labels: feature
