Repository adobe/S3Mock, pull requests merged in 2022-02, with the labels that each got.

#403 Use "docker buildx" for multi-platform builds.
  docker/build-docker-image.sh
  docker/pom.xml
  docker/push-docker-image.sh
  docker/start-buildkit.sh
  docker/stop-buildkit.sh
  pom.xml
Labels: feature

#404 Build and publish in "push-docker-image" profile
  docker/pom.xml
  docker/push-docker-image.sh
  pom.xml
Labels: feature

#406 Tagging
  integration-tests/src/test/java/com/adobe/testing/s3mock/its/TaggingResponsesV2IT.java
  server/src/main/java/com/adobe/testing/s3mock/FileStoreController.java
Labels: bug

#421 Change Docker image entrypoint to exec form
  docker/Dockerfile
Labels: housekeeping
